name: Reusable Build && Publish Template
on:
  # Allow the workflow to be run manually.
  workflow_dispatch:
    inputs:
      skip-sentry:
        required: false
        type: boolean
        default: false
  # No automations yet!!
  # 🚨 Be very careful with these, as this is a public repo.
  #    See: https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security

jobs:
  build:
    name: Build MgElectron
    strategy:
      matrix:
        include:
          - runner: [self-hosted, macOS, X64]
            platform-arch: 'darwin-x64'
          - runner: [self-hosted, macOS, ARM64]
            platform-arch: 'darwin-arm64'
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Prepare env
        uses: mightyapp/electron/.github/actions/prepare-build-env@aidan/rebase-15-x-y
        with:
          is-self-hosted: true
      - name: Build Electron && publish artifact
        uses: mightyapp/electron/.github/actions/build@aidan/rebase-15-x-y
        with:
          platform-arch: ${{ matrix.platform-arch }}
          sentry-token: ${{ secrets.SENTRY_TOKEN }}
